imports:
- path: Slurm-GCP.jinja

resources:
- name: Slurm-GCP
  type: Slurm-GCP.jinja
  properties:
    zone: us-central1-f

#    network_network: default
#
#    login_instanceCount  : 2
#    login_machineType    : n1-standard-4
#    login_bootDiskType   : pd-standard
#    login_bootDiskSizeGb : 10
#
#    # Controller
#    controller_machineType    : n1-standard-4
#    controller_bootDiskType   : pd-standard
#    controller_bootDiskSizeGb : 50
#
#    # Default Partition
#    input_partitionName    : default
#    input_staticNodeCount  : 0
#    input_maxNodeCount     : 100
#    compute_machineType    : n1-standard-16
#    compute_bootDiskType   : pd-standard
#    compute_bootDiskSizeGb : 10 
#
#    input_maxWallTime           : INFINITE
#    input_disableHyperthreading : False
#    input_preemptibleBursting   : False
#    input_computeLabel          : fluid-slurm
